/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'title' : string,
  'acknowledged' : boolean,
  'message' : string,
  'timestamp' : bigint,
  'severity' : string,
  'dismissed' : boolean,
}
export interface BackupRecord {
  'id' : bigint,
  'status' : string,
  'name' : string,
  'createdAt' : bigint,
  'sizeKB' : bigint,
}
export interface Notification {
  'id' : bigint,
  'notifType' : string,
  'read' : boolean,
  'message' : string,
  'timestamp' : bigint,
}
export interface SecurityEvent {
  'id' : bigint,
  'userName' : string,
  'action' : string,
  'userId' : string,
  'resourceCount' : bigint,
  'timestamp' : bigint,
  'riskLevel' : string,
  'riskScore' : bigint,
  'ipAddress' : string,
}
export interface SystemStatus {
  'totalEventsCount' : bigint,
  'lockReason' : string,
  'activeAlertsCount' : bigint,
  'locked' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acknowledgeAlert' : ActorMethod<[bigint], boolean>,
  'addEvent' : ActorMethod<
    [string, string, string, bigint, string, bigint, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearLogs' : ActorMethod<[], undefined>,
  'createBackup' : ActorMethod<[string, bigint], bigint>,
  'deleteBackup' : ActorMethod<[bigint], boolean>,
  'dismissAlert' : ActorMethod<[bigint], boolean>,
  'getAlerts' : ActorMethod<[], Array<Alert>>,
  'getBackups' : ActorMethod<[], Array<BackupRecord>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEvents' : ActorMethod<[], Array<SecurityEvent>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getSystemStatus' : ActorMethod<[], SystemStatus>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lockSystem' : ActorMethod<[string], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], boolean>,
  'restoreBackup' : ActorMethod<[bigint], boolean>,
  'seedDemoData' : ActorMethod<[], undefined>,
  'unlockSystem' : ActorMethod<[], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];