/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'acknowledged' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'severity' : IDL.Text,
  'dismissed' : IDL.Bool,
});
export const BackupRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'sizeKB' : IDL.Nat,
});
export const SecurityEvent = IDL.Record({
  'id' : IDL.Nat,
  'userName' : IDL.Text,
  'action' : IDL.Text,
  'userId' : IDL.Text,
  'resourceCount' : IDL.Nat,
  'timestamp' : IDL.Int,
  'riskLevel' : IDL.Text,
  'riskScore' : IDL.Nat,
  'ipAddress' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : IDL.Text,
  'read' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SystemStatus = IDL.Record({
  'totalEventsCount' : IDL.Nat,
  'lockReason' : IDL.Text,
  'activeAlertsCount' : IDL.Nat,
  'locked' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acknowledgeAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'addEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearLogs' : IDL.Func([], [], []),
  'createBackup' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'deleteBackup' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'dismissAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'getBackups' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lockSystem' : IDL.Func([IDL.Text], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'restoreBackup' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'seedDemoData' : IDL.Func([], [], []),
  'unlockSystem' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'acknowledged' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'severity' : IDL.Text,
    'dismissed' : IDL.Bool,
  });
  const BackupRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'sizeKB' : IDL.Nat,
  });
  const SecurityEvent = IDL.Record({
    'id' : IDL.Nat,
    'userName' : IDL.Text,
    'action' : IDL.Text,
    'userId' : IDL.Text,
    'resourceCount' : IDL.Nat,
    'timestamp' : IDL.Int,
    'riskLevel' : IDL.Text,
    'riskScore' : IDL.Nat,
    'ipAddress' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : IDL.Text,
    'read' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SystemStatus = IDL.Record({
    'totalEventsCount' : IDL.Nat,
    'lockReason' : IDL.Text,
    'activeAlertsCount' : IDL.Nat,
    'locked' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acknowledgeAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'addEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearLogs' : IDL.Func([], [], []),
    'createBackup' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'deleteBackup' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'dismissAlert' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'getBackups' : IDL.Func([], [IDL.Vec(BackupRecord)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(SecurityEvent)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getSystemStatus' : IDL.Func([], [SystemStatus], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lockSystem' : IDL.Func([IDL.Text], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'restoreBackup' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'seedDemoData' : IDL.Func([], [], []),
    'unlockSystem' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };